### ISSUE TITLE
arithmetic shift

### ISSUE THREAD

**Issue by MatthiasHeinz** [DancingSimpletons/writeups#1]
Shouldn't the ">>"-operator on signed variables be an arithmetic shift and therefore be sign-extending?

In contrast to your description, the MSB could therefore also be 1, if the number prior to the shift was a negative one. The overall key-space still remains 2^30, because the MSB is directly dependent on the bit next to it (they have to be equal); but you could have missed the actual key during brute-forcing by just testing positive 32-bit values.

**Comment by valhallasw** [comment]
Nice catch! Indeed, according to the [C# docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/right-shift-operator) it should be an arithmetic shift. 

Luckily enough, the actual key was a positive value (42 44 52 F6). However, in bits that's 
`0b01000010 01000100 01010010 11110110`
which seems inconsistent with starting with two ones. The reason for that is that `BitConverter.GetBytes` actually returns the value in little endian format. In other words, the key will be in the format

`0b???????0 ???????? ???????? aa??????`

while the loop in our Python script actually searched for
`0b0??????? ???????? ???????? ???????0`.

We were quite lucky that the result was compatible with the combination, i.e.,
`0b0??????0 ???????? ???????? aa?????0`

To correctly loop over the relevant values, we should have looped over

(big endian, both inclusive)
```
C0 00 00 00 ... FF FF FF FE (-1073741824 ... -2, steps of 2)
00 00 00 00 ... 4F FF FF FE (0 ... 1342177278, steps of 2)
```
to then interpret the numbers as little endian to create the key, i.e.,

```python
keys = range(-1073741824, 1342177278+1, 2)
for i in keys:
    key = i.to_bytes(4, "little") * 4  
    ....
```

I will update the writeup to clarify this.

**Comment by valhallasw** [comment]
Updated the writeup, thanks!

**Comment by MatthiasHeinz** [comment]
Cheers.
